name: Build tag
on:
  push:
    tags:
      - '*'
jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alpine-texlive-ja:${{ steps.extract_tag_name.outputs.tag }}
            ghcr.io/${{ github.repository_owner }}/texlive-ja:${{ steps.extract_tag_name.outputs.tag }}-alpine
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository_owner }}/texlive-ja-textlint:${{ steps.extract_tag_name.outputs.tag }}-debian
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:${{ steps.extract_tag_name.outputs.tag }}-debian
