name: Build latest
on:
  push:
    branches:
      - main

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alpine-texlive-ja-textlint:latest
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:alpine
  build-debian:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:latest
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:debian
