name: Build latest
on:
  push:
    branches:
      - main

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/alpine-${{ env.CI_REPOSITORY_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.CI_REPOSITORY_NAME }}:alpine
  build-debian:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.CI_REPOSITORY_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.CI_REPOSITORY_NAME }}:debian
