name: Build PR
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:alpine
      - name: Test
        run: |
          docker run --rm -v ${PWD}/tests:/workdir ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:alpine \
            sh -c 'latexmk -C main.tex && latexmk main.tex && latexmk -c main.tex';
      - name: Upload result
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: alpine
          path: ./tests/main.pdf
  build-alpine-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          platforms: linux/arm64

  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:debian
      - name: Test
        run: |
          docker run --rm -v ${PWD}/tests:/workdir ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:debian \
            sh -c 'latexmk -C main.tex && latexmk main.tex && latexmk -c main.tex';
      - name: Upload result
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: debian
          path: ./tests/main.pdf
  build-debian-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          platforms: linux/arm64
