name: Build PR
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./alpine/
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:alpine
      - name: Test
        run: |
          docker run --rm -v ${PWD}/tests:/workdir ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:alpine \
            sh -c 'latexmk -C main.tex && latexmk main.tex && latexmk -c main.tex';
      - name: Upload result
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: alpine
          path: ./tests/main.pdf
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:debian
      - name: Test
        run: |
          docker run --rm -v ${PWD}/tests:/workdir ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:debian \
            sh -c 'latexmk -C main.tex && latexmk main.tex && latexmk -c main.tex';
      - name: Upload result
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: debian
          path: ./tests/main.pdf
  build-debian-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          platforms: linux/arm64
